DROP TABLE IF EXISTS `mango_order_0`;
CREATE TABLE `mango_order_0` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `mango_order_1`;
CREATE TABLE `mango_order_1` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `mango_order_2`;
CREATE TABLE `mango_order_2` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `mango_order_3`;
CREATE TABLE `mango_order_3` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `mango_order_4`;
CREATE TABLE `mango_order_4` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `mango_order_5`;
CREATE TABLE `mango_order_5` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `mango_order_6`;
CREATE TABLE `mango_order_6` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `mango_order_7`;
CREATE TABLE `mango_order_7` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';

DROP TABLE IF EXISTS `mango_order_8`;
CREATE TABLE `mango_order_8` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';

DROP TABLE IF EXISTS `mango_order_9`;
CREATE TABLE `mango_order_9` (
  `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '订单号',
  `MERCHANT` VARCHAR(12) NOT NULL COMMENT '业务方',
  `MERCHANT_ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务方订单号',
  `AMOUNT` DECIMAL (12,2)  NOT NULL COMMENT '金额',
  `CREATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近发送时间',
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `MERCHANT_AND_ORDER_KEY` (`MERCHANT`,`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';
